// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTQM__CAR_API.CTQM_CAR.Domain;

public partial class Car
{
    public Guid CarId { get; set; }

    public string CarName { get; set; }

    public string CarModel { get; set; }

    public string CarClass { get; set; }

    public string CarEngine { get; set; }

    public int CarAmount { get; set; }

    public double CarPrice { get; set; }

    public string MoTa { get; set; }

    public string Head1 { get; set; }

    public string MoTa2 { get; set; }

    public string Image1 { get; set; }

    public string Image2 { get; set; }

    public string Image3 { get; set; }

    public string Image4 { get; set; }

    public virtual ICollection<CarDetail> CarDetails { get; set; } = new List<CarDetail>();

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}