// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTQM__CAR_API.CTQM_CAR.Domain;

public partial class Car
{
    public Guid CarId { get; set; }

    public string? CarName { get; set; }

    public string? CarModel { get; set; }

    public string? CarClass { get; set; }

    public string? CarEngine { get; set; }

    public int? CarAmount { get; set; }

    public double? CarPrice { get; set; }

    public string? MoTa { get; set; }

    public string? Head1 { get; set; }

    public string? MoTa2 { get; set; }
}