// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTQM__CAR_API.CTQM_CAR.Domain;

public partial class Cart
{
    public Guid CartId { get; set; }

    public Guid CustomerId { get; set; }

    public Guid CarId { get; set; }

    public int Amount { get; set; }

    public double Price { get; set; }

    public virtual Car Car { get; set; }

    public virtual Customer Customer { get; set; }
}