// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTQM__CAR_API.CTQM_CAR.Domain;

public partial class Customer
{
    public Guid CustomerId { get; set; }

    public string CustomerName { get; set; }

    public string CustomerPhone { get; set; }

    public string CustomerAddress { get; set; }

    public DateTime CustomerDate { get; set; }

    public string CustomerLicense { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerPassword { get; set; }

    public bool? CustomerVaild { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}