// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTQM__CAR_API.CTQM_CAR.Domain;

public partial class Order
{
    public Guid OrderId { get; set; }

    public Guid CarId { get; set; }

    public DateTime OrderDate { get; set; }

    public string OrderStatus { get; set; }

    public int Amount { get; set; }

    public double TotalPrice { get; set; }

    public Guid CustomerId { get; set; }
}